/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.route;

/**
 *
 * @author Ashutosh Pandey
 */
public class RouteFinder extends javax.swing.JDialog {

    /**
     * Creates new form RouteFinder
     */
    public RouteFinder(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Utility.centerScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSourceCity = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbDestinationCity = new javax.swing.JComboBox();
        btnSearchPath = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        lbMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 290));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Route Finder");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 230, 50);

        jLabel2.setText("Source");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 40, 16);

        getContentPane().add(cmbSourceCity);
        cmbSourceCity.setBounds(140, 90, 170, 22);

        jLabel4.setText("Destination");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 63, 16);

        getContentPane().add(cmbDestinationCity);
        cmbDestinationCity.setBounds(140, 130, 170, 22);

        btnSearchPath.setText("Find Route");
        btnSearchPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPathActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchPath);
        btnSearchPath.setBounds(40, 180, 100, 25);

        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btClose);
        btClose.setBounds(150, 180, 80, 25);
        getContentPane().add(lbMessage);
        lbMessage.setBounds(40, 230, 270, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPathActionPerformed
        findRoute();
    }//GEN-LAST:event_btnSearchPathActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RouteFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RouteFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RouteFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RouteFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RouteFinder dialog = new RouteFinder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btnSearchPath;
    private javax.swing.JComboBox cmbDestinationCity;
    private javax.swing.JComboBox cmbSourceCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbMessage;
    // End of variables declaration//GEN-END:variables

    private void findRoute() {
        
    }
}
